name: Practice workflow dispatch

on: [workflow_dispatch]

jobs:
  job1:
    name: printing another shell 
    runs-on: ubuntu-latest
    
    steps: 
    - name: case script
      run: |
        
        #!/bin/bash
        
        echo Executing workflow dispatch
        i=3
        
        case $i in
          2)date;;
          3)pwd;;
          *) echo invalid
          
        esac
      
